from setuptools import setup, find_packages

setup(
    name="cmip6-visualizer",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        'affine>=2.4.0',
        'aiohttp>=3.10.10',
        'beautifulsoup4>=4.12.3',
        'bqplot>=0.12.43',
        'branca>=0.7.2',
        'earthengine-api>=1.3.1',
        'ee-extra>=0.0.15',
        'Fiona>=1.9.1',
        'folium>=0.18.0',
        'GDAL>=3.6.2',
        'geeadd>=0.5.6',
        'geemap>=0.35.1',
        'geocoder>=1.38.1',
        'geopandas>=0.14.4',
        'ipykernel>=6.29.5',
        'ipyleaflet>=0.19.2',
        'ipython>=8.29.0',
        'ipywidgets>=8.1.5',
        'jupyter_client>=8.6.3',
        'jupyter_core>=5.7.2',
        'jupyterlab>=4.3.0',
        'matplotlib>=3.9.2',
        'numpy>=1.26.4',
        'pandas>=2.2.3',
        'pillow>=11.0.0',
        'plotly>=5.24.1',
        'pyproj>=3.6.1',
        'python-box>=7.2.0',
        'rasterio>=1.3.10',
        'requests>=2.32.3',
        'scikit-learn>=1.5.2',
        'scipy>=1.14.1',
        'seaborn>=0.13.2',
        'shapely>=2.0.5',
        'tqdm>=4.67.0',
        'xyzservices>=2024.9.0'
    ],
    python_requires='>=3.11,<3.12',
    author="Saurav Bhattarai",
    author_email="saurav.bhattarai.1999@gmail.com",
    description="CMIP6 Visualization Tool",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: GIS",
        "Topic :: Scientific/Engineering :: Visualization",
    ],
)